spring:
  datasource:
    url: jdbc:mysql://localhost:3306/resume_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: resume_analyzer
    password: mypd
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
